trigger:
- none

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Dev
    displayName: 'Dev'
    variables:
      - group: ARM
    jobs:
      - deployment: PreRequisites
        displayName: 'Deploy Pre-Requisite Infrastructure'
        environment: ARM
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureResourceManagerTemplateDeployment
                  displayName: 'Deploy resource group'
                  inputs:
                    deploymentScope: 'Subscription'
                    azureResourceManagerConnection: 'sp-devops-pipeline'
                    subscriptionId: '$(ARM.subscrption_id)'
                    location: '$(ARM.resource_group_location)'
                    templateLocation: 'Linked artifact'
                    csmFile: 'Platform/ARM-Templates/ResurceGroup/template.json'
                    csmParametersFile: 'Platform/ARM-Templates/ResourceGroup/parameter.json'
                    overrideParameters: '-rgLocation "$(ARM.resource_group_location)" -rgName "$(ARM.resource_group_name)"'
                    deploymentMode: 'Incremental'